### PR TITLE
lawnicons: Dynamically track all our icons [1/2]

### PR DESCRIPTION
**Pull request by Maitreya29**
It's a lot of hassle to maintain a different fork of icons which needs to be manually updated every few days. This will track icons directly from Lawnchair's repos so that the icons are automatically updated whenever lawnchair merges new icons.

### CODE REVIEW

**Comment by ghost** [comment]
Looks good!

**Comment by sarthakroy2002** [comment]
Looks Fine.

**Comment by Maitreya29** [comment]
Closing this due to inactivity and a lack of response.

**Comment by kdrag0n** [comment]
Sorry, I didn't get a chance to look into this until now. I like the idea to auto-update Lawnicons as I've been forgetting to do it, but this results in unreproducible builds (i.e. same version will have different icons depending on when it was synced). Perhaps auto-updating it but still keeping it as a fork would be better.

**Pull request closed without merging**
